version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/e2eTest/playwright"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
