---
exclude_paths:
  - "**/__tests__/**"
  - "infra/**"
  - "*.md"
  - "web/vite.config.ts"
  - "web/config/**"
  - "**/*.stories.tsx"
  - ".husky"
  - ".github"
  - "web/.storybook/**"
  - "web/viteEnv/**"
  - "test/e2e/data/**"
  - "test/e2e/flyway/**"
  - "web/Dockerfile"
