export type DefineDiagramsActionType = "idle" | "enlarge_diagram_rectangle" | "enlarge_diagram_polygon";

export enum DefineDiagramMenuLabels {
  Delete = "Delete",
  ZoomIn = "Zoom in",
  ZoomOut = "Zoom out",
  ZoomCentre = "Zoom centre",
  SelectRTLines = "Select RT lines",
  AddRTLines = "Add RT lines",
  DrawRTBoundary = "Draw RT boundary",
  DrawAbuttal = "Draw abuttal",
  SelectLine = "Select line",
  DefinePrimaryDiagram = "Define primary diagram",
  DefinePrimaryDiagramByRectangle = "Define primary diagram by rectangle",
  DefinePrimaryDiagramByPolygon = "Define primary diagram by polygon",
  DefineNonPrimaryDiagram = "Define non-primary diagram",
  DefineNonPrimaryDiagramByRectangle = "Define non-primary diagram by rectangle",
  DefineNonPrimaryDiagramByPolygon = "Define non-primary diagram by polygon",
  DefineSurveyDiagram = "Define survey diagram",
  DefineSurveyDiagramByRectangle = "Define survey diagram by rectangle",
  DefineSurveyDiagramByPolygon = "Define survey diagram by polygon",
  SelectDiagram = "Select diagram",
  LabelDiagrams = "Label diagrams",
  EnlargeDiagram = "Enlarge diagram",
  EnlargeByRectangle = "Enlarge by rectangle",
  EnlargeByPolygon = "Enlarge by polygon",
  ReduceDiagram = "Reduce diagram",
  ReduceByRectangle = "Reduce by rectangle",
  ReduceByPolygon = "Reduce by polygon",
  ManageLabels = "Manage labels",
  DropdownIcon = "Dropdown icon",
}
