#!/bin/bash
function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'web/package-lock.json'; then
  echo "📦 The web package-lock.json changed. Run npm install in web folder to bring your dependencies up to date."
fi

if changed 'test/e2e/package-lock.json'; then
  echo "📦 The e2e package-lock.json changed. Run npm install in e2e/test folder to bring your dependencies up to date."
fi

if changed 'infra/package-lock.json'; then
  echo "📦 The infra package-lock.json changed. Run npm install in infra folder to bring your dependencies up to date."
fi
