name: Conventional Commit Checker

on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize]

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR contains JIRA ticket and conventional commit type
        uses: linz/action-pull-request-lint@4744d5a3ab84000afc4eb5dc98b7fd19d7682fff # v1.1.0
        with:
          conventional: "error"
          jira: "error"
          jira-projects: "SJ,SURVEY,SRVPUW,ENABLE"
