name: Conventional Commit Checker

on:
  pull_request:
    branches: [ master ]
    types: [ opened, edited, synchronize ]

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-title-regex: "^(.+)(?:(([^)s]+)))?: ([A-Z]+)-([0-9]+): (.+)"
          pr-body-regex: ".*"
