# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  merge_group:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'web/**'
  push:
    branches:
      - 'master'
    paths:
      - 'web/**'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest-4-cores
    # Job steps
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # for pull requests, checkout the head of the branch instead of the merge commit
          # so that turbosnap is able to determine the changes
          # see https://github.com/chromaui/chromatic-cli/issues/731
          ref: ${{ github.event.pull_request.head.ref }}
          # check out the full history so that turbosnap can determine the changes
          fetch-depth: 0
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        working-directory: ./web
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_GITHUB_PACKAGES }}
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        timeout-minutes: 60
        uses: chromaui/action@v11
        # Chromatic GitHub Action options
        with:
          workingDir: web
          onlyChanged: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
