name: CI - Survey Plangen Front End

on:
  merge_group:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  frontend-ci:
    uses: linz/github-action-shared-library/.github/workflows/frontend-ci.yml@master # https://github.com/linz/github-action-shared-library/blob/master/docs/frontend-ci.md
    with:
      aws-github-ci-role-arn: 'arn:aws:iam::964632537160:role/landonline-survey-plangen-landonlinesurveyplangenci-LQCKTV18EcJb'
      sourcemapDisable: true

      # Release config
      shouldCreateRelease: ${{ github.ref == 'refs/heads/master' }}
      releaseChangePath: "web .github/workflows"

      # Snyk
      snykCheckEnable: true
      snykOrgName: survey-jay

      # e2e tests
      e2eTestRunner: ubuntu-latest-16-cores
      e2eDir: ./test/e2e
      e2eLintCommand: "npm run lint"
      e2eTestReportDir: "test/e2e/output"
      e2etestDataLoadEnable: true
      e2etestDataLoadDir: ./test/e2e/flyway
      e2etestDataLoadScript: chmod +x ./gradlew && ./gradlew flywayMigrate -i -Pflyway.configFiles=flyway.conf -Pflyway.user=${DB_USERNAME} -Pflyway.password=${DB_PASSWORD}

      # These are needed for playwright to work
      image: "step/survey/step-landonline-web-survey-plan-generation-fe"
      imageTag: 'latest'

      # Push coverage to codacy
      codacyDisable: false
    secrets: inherit

  upload-sourcemaps:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [frontend-ci]
    uses: linz/github-action-shared-library/.github/workflows/upload-source-map-workflow.yml@master
    strategy:
      matrix:
        include:
          - appId: 1835041279 # New Relic: https://onenr.io/02R56LLxrjb
            domain: 'kartoffel.dev.landonline.govt.nz'
          - appId: 1835041280 # New Relic: https://onenr.io/0LwGV11VeQ6
            domain: 'kumara.env.landonline.govt.nz'
          - appId: '1835050606' # New Relic: https://onenr.io/0qQadyK2Zj1
            domain: 'app.landonline.govt.nz'
    with:
      appId: ${{ matrix.appId }}
      urlPathsToHostedFiles: 'https://${{ matrix.domain }}/plan-generation/public'
      sourceMapDir: 'web/build/public'
    secrets:
      apiKey: ${{ secrets.NEW_RELIC_DEPLOYMENT_API_KEY }}

