name: Reusable workflow to trigger frontend deploys to one environment

on:
  workflow_call:
    inputs:
      deployment_environment:
        required: true
        type: string
      deployment_role_arn:
        required: true
        type: string

jobs:
  s3-deploy-frontend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: deploy frontend-deploy-to-s3
        uses: linz/github-action-shared-library/.github/actions/frontend-deploy-to-s3@master
        with:
          aws-deployment-role-arn: ${{ inputs.deployment_role_arn }}
          github-token: ${{ secrets.STEP_GITHUB_ACTION_TOKEN }}
          bucket: "linz-landonline-survey-plangen-${{ inputs.deployment_environment }}"
          slackBotUserOAuthAccessToken: ${{ secrets.SLACK_STEP_GITHUB_ACTION_BOT_TOKEN }}
          slackChannel: team-step-survey-plangen-build
